export default {
  nav: { work: 'Work', about: 'About', home: 'Portfolio home', primary: 'Primary navigation', mobile: 'Mobile navigation', title: 'Navigation', description: 'Portfolio navigation, language and theme controls', open: 'Open menu', close: 'Close menu', skip: 'Skip to content' },
  language: { switchTo: 'Switch to Persian', short: 'FA', control: 'Language' },
  theme: { label: 'Color theme', light: 'Switch to light mode', dark: 'Switch to dark mode' },
  common: { behance: 'Behance', cv: 'CV', downloadCv: 'Download CV', email: 'Email', external: 'opens in a new tab', downloadPdf: 'downloads PDF' },
  home: {
    seoTitle: 'Amir Zare — Senior Product & UX Designer', seoDescription: 'Amir Zare’s product design portfolio, focused on fintech, investment and financial-market products.', heroBefore: 'Designing clarity', heroAccent: 'into', heroAfter: 'complex financial products.', heroPositioning: 'Product designer focused on fintech, investment and financial markets.', selectedWork: 'Selected projects', about: 'About', focus: 'Focus', focusValue: 'Fintech · Investment · Crypto', practice: 'Practice', practiceValue: 'End-to-end product design', approach: 'Approach', approachValue: 'Research, design and testing', status: 'Status', workDescription: 'Three financial-product projects, covering the problem, key decisions and final work.', viewAll: 'All projects', expertise: 'Expertise', aboutLabel: 'About', aboutHeadline: 'I turn complex financial experiences into clear, trustworthy journeys.', aboutSummary: 'I help people understand financial information, make confident decisions and complete their tasks without unnecessary friction.', moreAbout: 'Read more about me',
    snapshot: { product: 'Product type', role: 'My role', timeline: 'Timeline', scope: 'Project scope', scopeValue: 'Architecture to handoff', status: 'Status' },
    decisions: {
      label: 'Design decisions', title: 'Three important design decisions', intro: 'These decisions made the journeys shorter and the financial information easier to understand.', link: 'See the decisions',
      items: {
        progressive: 'Information appears when users need it, instead of arriving all at once in a long form.',
        identity: 'Rose and Afran look different, but use the same purchase and management flow.',
        hierarchy: 'Amounts, current value and decision-critical information appear before supporting detail.'
      }
    },
    working: { label: 'How I work', title: 'From understanding the problem to shipping the product', steps: { frame: 'Understand the problem', structure: 'Design the solution', delivery: 'Test and hand off' } }
  },
  work: { seoTitle: 'Selected Projects — Amir Zare', seoDescription: 'Selected fintech and investment product design case studies.', eyebrow: 'Project index', titleBefore: 'Selected', titleAccent: 'projects', featured: 'Featured case study', featuredDescription: 'The complete project narrative for this portfolio release.', secondary: 'Selected projects', visual: 'Visual work', visualDescription: 'Selected visual design work.' },
  about: { seoTitle: 'About Amir Zare — Senior Product Designer', seoDescription: 'Amir Zare is a Tehran-based Senior Product Designer focused on fintech, investment, crypto and financial-market products.', label: 'About', headline: 'I make complex financial products easier to understand and use.', currentFocus: 'Focus', currentFocusValue: 'Fintech · Investment · Crypto products', basedIn: 'Based in', experience: 'Work experience', outcomes: 'Measured outcomes', outcomesNote: 'These figures come from my CV, with the relevant project named beside each result.', capabilities: 'Skills & tools', education: 'Education', degree: 'Bachelor of Accounting', university: 'Islamic Azad University Tehran · 2011—2014', learning: 'Courses', learningList: 'Google UX Cert · NN/g · IxDF' },
  project: { view: 'View case study', open: 'Open project', imagePlaceholder: 'Project image placeholder', coverPlaceholder: '{title} cover image placeholder', heroPlaceholder: 'Case study hero image placeholder', outline: 'Case study outline', context: 'Context', challenge: 'Challenge', research: 'Research', decisions: 'Decisions', solution: 'Solution', validation: 'Validation', learnings: 'Learnings', role: 'Role', timeline: 'Timeline', team: 'Team', industry: 'Industry', responsibilities: 'Responsibilities', previous: 'Previous project', next: 'Next project', navigation: 'Project navigation', caseStudySuffix: 'Case Study', notFound: 'Project not found' },
  footer: { eyebrow: 'Working on a complex product? I’d be happy to talk.', headline: 'Available for product design work.' }
}
