export default {
  nav: { work: 'Work', about: 'About', home: 'Portfolio home', primary: 'Primary navigation', mobile: 'Mobile navigation', title: 'Navigation', description: 'Portfolio navigation, language and theme controls', open: 'Open menu', close: 'Close menu', skip: 'Skip to content' },
  language: { switchTo: 'Switch to Persian', short: 'FA', control: 'Language' },
  theme: { label: 'Color theme', light: 'Switch to light mode', dark: 'Switch to dark mode' },
  common: { linkedin: 'LinkedIn', behance: 'Behance', cv: 'CV', downloadCv: 'Download CV', email: 'Email', phone: 'Phone', external: 'opens in a new tab', downloadPdf: 'downloads PDF' },
  home: { seoTitle: 'Amir Zare — Senior Product Designer', seoDescription: 'Senior Product Designer specialising in fintech, investment and crypto platforms.', heroBefore: 'Designing clarity', heroAccent: 'into', heroAfter: 'complex financial products.', selectedWork: 'Selected work', about: 'About', focus: 'Focus', focusValue: 'Fintech · Investment · Crypto', practice: 'Practice', practiceValue: 'End-to-end product design', approach: 'Approach', approachValue: 'AI-native workflow', status: 'Status', workDescription: 'Selected product work across financial platforms, conversion, interaction design and systems. Full case studies are currently being documented.', viewAll: 'View all projects', expertise: 'Expertise', aboutLabel: 'About', aboutHeadline: 'Turning complex financial systems into clear product experiences.', moreAbout: 'More about me' },
  work: { seoTitle: 'Selected Work — Amir Zare', seoDescription: 'Product design work across fintech, investment, crypto, conversion and design systems.', eyebrow: 'Selected projects · 2026', titleBefore: 'Selected', titleAccent: 'work', intro: 'A working index of product design engagements. Titles and categories are temporary; full context, decisions and outcomes will be added in the next content phase.' },
  about: { seoTitle: 'About — Amir Zare', seoDescription: 'Amir Zare is a Senior Product Designer specialising in fintech, investment and crypto platforms.', label: 'About', headline: 'Turning complex financial systems into clear product experiences.', portrait: 'Portrait · TODO', portraitLabel: 'Portrait to be provided', currentFocus: 'Current focus', currentFocusValue: 'Fintech · Investment · Crypto platforms', basedIn: 'Based in', experience: 'Experience', outcomes: 'Selected outcomes', outcomesNote: 'Quantitative outcomes reported in the CV. Project attribution is preserved exactly as supplied.', capabilities: 'Capabilities & tools', education: 'Education', degree: 'Bachelor of Accounting', university: 'Islamic Azad University Tehran · 2011—2014', learning: 'Continued learning', learningList: 'Google UX Cert · NN/g · IxDF', learningTodo: 'Specific course titles and completion dates: TODO' },
  project: { view: 'View case study', open: 'Open project', imagePlaceholder: 'Project image placeholder', coverPlaceholder: '{title} cover image placeholder', heroPlaceholder: 'Case study hero image placeholder', outline: 'Case study outline', context: 'Context', challenge: 'Challenge', research: 'Research', decisions: 'Decisions', solution: 'Solution', validation: 'Validation', learnings: 'Learnings', role: 'Role', timeline: 'Timeline', team: 'Team', industry: 'Industry', responsibilities: 'Responsibilities', previous: 'Previous project', next: 'Next project', navigation: 'Project navigation', caseStudySuffix: 'Case Study', notFound: 'Project not found' },
  footer: { eyebrow: 'Let’s make complex products feel clear.', headline: 'Available for the right conversation.' }
}
