export default {
  nav: { work: 'Work', about: 'About', home: 'Portfolio home', primary: 'Primary navigation', mobile: 'Mobile navigation', title: 'Navigation', description: 'Portfolio navigation, language and theme controls', open: 'Open menu', close: 'Close menu', skip: 'Skip to content' },
  language: { switchTo: 'Switch to Persian', short: 'FA', control: 'Language' },
  theme: { label: 'Color theme', light: 'Switch to light mode', dark: 'Switch to dark mode' },
  common: { behance: 'Behance', cv: 'CV', downloadCv: 'Download CV', email: 'Email', external: 'opens in a new tab', downloadPdf: 'downloads PDF' },
  home: {
    seoTitle: 'Amir Zare — Senior Product & UX Designer', seoDescription: 'The portfolio of Amir Zare, a Senior Product and UX Designer specialising in fintech, investment, crypto and financial-market platforms.', heroBefore: 'Designing clarity', heroAccent: 'into', heroAfter: 'complex financial products.', heroPositioning: 'Specialising in fintech, investment and financial-market platforms.', selectedWork: 'Selected projects', about: 'About', focus: 'Focus', focusValue: 'Fintech · Investment · Crypto', practice: 'Practice', practiceValue: 'End-to-end product design', approach: 'Approach', approachValue: 'AI-native workflow', status: 'Status', workDescription: 'Selected case studies from complex financial products and service experiences.', viewAll: 'View all projects', expertise: 'Expertise', aboutLabel: 'About', aboutHeadline: 'Turning complex financial systems into simple, fluid experiences.', aboutSummary: 'I turn financial complexity into simple, trustworthy journeys that help people understand, decide, and move forward with confidence.', moreAbout: 'More about me',
    snapshot: { product: 'Product type', role: 'My role', timeline: 'Timeline', scope: 'Project scope', scopeValue: 'Architecture to handoff', status: 'Status' },
    decisions: {
      label: 'Key decisions', title: 'Three decisions that shaped the experience', intro: 'From framing the problem to the final product experience, these decisions guided the structure of the work.', link: 'View the full rationale',
      items: {
        progressive: 'Information appears only when it is needed, keeping the journey clear, focused, and free from unnecessary friction.',
        identity: 'Each product keeps a distinct visual identity, while shared interaction patterns make the experience feel familiar and consistent.',
        hierarchy: 'The most important information is given priority so decisions can be made faster, more clearly, and with greater confidence.'
      }
    },
    working: { label: 'How I work', title: 'A clear path from problem to product', steps: { frame: 'Frame the problem', structure: 'Structure the solution', delivery: 'Review and handoff' } }
  },
  work: { seoTitle: 'Selected Projects — Amir Zare', seoDescription: 'Selected fintech and investment product design case studies.', eyebrow: 'Project index', titleBefore: 'Selected', titleAccent: 'projects', featured: 'Featured case study', featuredDescription: 'The complete project narrative for this portfolio release.', secondary: 'Selected projects', visual: 'Visual work', visualDescription: 'Selected visual design work.' },
  about: { seoTitle: 'About Amir Zare — Senior Product Designer', seoDescription: 'About Amir Zare, a Tehran-based Senior Product and UX Designer specialising in fintech, investment, crypto and financial-market platforms.', label: 'About', headline: 'Turning complex financial systems into simple, fluid experiences.', currentFocus: 'Current focus', currentFocusValue: 'Fintech · Investment · Crypto platforms', basedIn: 'Based in', experience: 'Experience', outcomes: 'Selected outcomes', outcomesNote: 'Quantitative outcomes reported in the CV. Project attribution is preserved exactly as supplied.', capabilities: 'Capabilities & tools', education: 'Education', degree: 'Bachelor of Accounting', university: 'Islamic Azad University Tehran · 2011—2014', learning: 'Continued learning', learningList: 'Google UX Cert · NN/g · IxDF' },
  project: { view: 'View case study', open: 'Open project', imagePlaceholder: 'Project image placeholder', coverPlaceholder: '{title} cover image placeholder', heroPlaceholder: 'Case study hero image placeholder', outline: 'Case study outline', context: 'Context', challenge: 'Challenge', research: 'Research', decisions: 'Decisions', solution: 'Solution', validation: 'Validation', learnings: 'Learnings', role: 'Role', timeline: 'Timeline', team: 'Team', industry: 'Industry', responsibilities: 'Responsibilities', previous: 'Previous project', next: 'Next project', navigation: 'Project navigation', caseStudySuffix: 'Case Study', notFound: 'Project not found' },
  footer: { eyebrow: 'Let’s make complex products feel clear.', headline: 'Available for the right conversation.' }
}
