export default {
  nav: { work: 'پروژه‌ها', about: 'درباره من', home: 'خانه نمونه‌کار', primary: 'ناوبری اصلی', mobile: 'ناوبری موبایل', title: 'منو', description: 'ناوبری نمونه‌کار، زبان و تنظیمات رنگ', open: 'باز کردن منو', close: 'بستن منو', skip: 'رفتن به محتوای اصلی' },
  language: { switchTo: 'تغییر زبان به انگلیسی', short: 'EN', control: 'زبان' },
  theme: { label: 'رنگ‌بندی', light: 'تغییر به حالت روشن', dark: 'تغییر به حالت تیره' },
  common: { linkedin: 'LinkedIn', behance: 'Behance', cv: 'رزومه', downloadCv: 'دریافت رزومه', email: 'ایمیل', phone: 'تلفن', external: 'در زبانه جدید باز می‌شود', downloadPdf: 'فایل PDF دریافت می‌شود' },
  home: { seoTitle: 'امیر زارع — طراح ارشد محصول', seoDescription: 'طراح ارشد محصول، متخصص در پلتفرم‌های فین‌تک، سرمایه‌گذاری و رمزارز.', heroBefore: 'طراحی وضوح', heroAccent: 'در دل', heroAfter: 'محصولات مالی پیچیده.', selectedWork: 'پروژه‌های منتخب', about: 'درباره من', focus: 'حوزه تمرکز', focusValue: 'فین‌تک · سرمایه‌گذاری · رمزارز', practice: 'تخصص', practiceValue: 'طراحی سرتاسری محصول', approach: 'رویکرد', approachValue: 'فرایند مبتنی بر هوش مصنوعی', status: 'وضعیت', workDescription: 'منتخبی از پروژه‌های محصول در پلتفرم‌های مالی، بهینه‌سازی تبدیل، طراحی تعامل و سیستم‌ها. مستندسازی کامل مطالعات موردی در دست انجام است.', viewAll: 'مشاهده همه پروژه‌ها', expertise: 'تخصص‌ها', aboutLabel: 'درباره من', aboutHeadline: 'تبدیل سیستم‌های مالی پیچیده به تجربه‌های محصول روشن.', moreAbout: 'بیشتر درباره من' },
  work: { seoTitle: 'پروژه‌های منتخب — امیر زارع', seoDescription: 'پروژه‌های طراحی محصول در فین‌تک، سرمایه‌گذاری، رمزارز، بهینه‌سازی تبدیل و سیستم‌های طراحی.', eyebrow: 'پروژه‌های منتخب · ۲۰۲۶', titleBefore: 'پروژه‌های', titleAccent: 'منتخب', intro: 'فهرستی در حال تکمیل از پروژه‌های طراحی محصول. عنوان‌ها و دسته‌بندی‌های موقت حفظ شده‌اند و زمینه، تصمیم‌ها و نتایج کامل در مرحله بعد اضافه می‌شوند.' },
  about: { seoTitle: 'درباره امیر زارع', seoDescription: 'امیر زارع طراح ارشد محصول و متخصص پلتفرم‌های فین‌تک، سرمایه‌گذاری و رمزارز است.', label: 'درباره من', headline: 'تبدیل سیستم‌های مالی پیچیده به تجربه‌های محصول روشن.', portrait: 'تصویر پرتره · TODO', portraitLabel: 'تصویر پرتره بعداً اضافه می‌شود', currentFocus: 'تمرکز فعلی', currentFocusValue: 'پلتفرم‌های فین‌تک · سرمایه‌گذاری · رمزارز', basedIn: 'محل فعالیت', experience: 'سوابق حرفه‌ای', outcomes: 'نتایج منتخب', outcomesNote: 'اعداد گزارش‌شده در رزومه؛ انتساب هر نتیجه به پروژه، مطابق منبع حفظ شده است.', capabilities: 'توانمندی‌ها و ابزارها', education: 'تحصیلات', degree: 'کارشناسی حسابداری', university: 'دانشگاه آزاد اسلامی تهران · ۲۰۱۱—۲۰۱۴', learning: 'یادگیری مستمر', learningList: 'Google UX Cert · NN/g · IxDF', learningTodo: 'عنوان دقیق دوره‌ها و تاریخ پایان: TODO برای بازبینی' },
  project: { view: 'مشاهده مطالعه موردی', open: 'باز کردن پروژه', imagePlaceholder: 'جای تصویر پروژه', coverPlaceholder: 'جای تصویر پروژه {title}', heroPlaceholder: 'جای تصویر اصلی مطالعه موردی', outline: 'ساختار مطالعه موردی', context: 'زمینه', challenge: 'چالش', research: 'پژوهش', decisions: 'تصمیم‌ها', solution: 'راه‌حل', validation: 'اعتبارسنجی', learnings: 'آموخته‌ها', role: 'نقش', timeline: 'بازه زمانی', team: 'تیم', industry: 'صنعت', responsibilities: 'مسئولیت‌ها', previous: 'پروژه قبلی', next: 'پروژه بعدی', navigation: 'ناوبری پروژه‌ها', caseStudySuffix: 'مطالعه موردی', notFound: 'پروژه پیدا نشد' },
  footer: { eyebrow: 'بیایید محصولات پیچیده را روشن و قابل‌فهم کنیم.', headline: 'برای گفت‌وگویی مناسب آماده‌ام.' }
}
